name: Curriculum Solution Branch Splitter

on:
  workflow_dispatch: 
  push:
    branches: curriculum
    paths: index.ipynb

jobs:
  Test_remote_action:
    uses: learn-co-curriculum/dsc-github-actions-files/.github/workflows/branch_split.yml@v1.0.11
    secrets: inherit
   
